stages:
  - pre-build
  - pre-build-test
  - build
  - cleanup

image: $REGISTRY/evfoundation-executor-docker13:node8alpine36

variables:
  REGISTRY: registry.${DOMAIN_NAME}

before_script:
  - export project=${CI_PROJECT_NAME//[^[:alnum:]]/}
  - export group=${CI_PROJECT_NAMESPACE//[^[:alnum:]]/}
  - export branch=${CI_BUILD_REF_NAME//[^[:alnum:]]/}
  - export pipelineId=${CI_PIPELINE_ID//[^[:alnum:]]/}

npminstall:
  stage: pre-build
  script:
    - echo "Performing code style check..."
    - status_eslint=0
    - exit_status=0
    - npm config set registry http://registry.npmjs.org/
    - npm set progress=false
    - time npm install eslint babel-eslint --no-optional
    - if npm run lint; then status_eslint=0; else status_eslint=1; fi
    - if [ $status_eslint == 1 ]; then exit_status=1 && echo "esLint errors exist"; fi
    - if [ $exit_status == 1 ]; then exit $exit_status; fi
    - echo "Code style check done successfully"
    - time npm install --no-optional
    - echo "Node Modules Installed"
  artifacts:
    untracked: true
    expire_in: 2h
    paths:
      - node_modules/
  tags:
    - CEP_RUNNER


mongotest:
  stage: pre-build-test
  script:
    - mocha test/test.js
  artifacts:
    untracked: true
    expire_in: 2h
    paths:
      - coverage/
    when: on_failure
  tags:
    - CEP_RUNNER

postgrestest:
  stage: pre-build-test
  script:
    - echo 'Performing PostgreSQL Test'
  tags:
    - CEP_RUNNER    
  tags:
    - CEP_RUNNER
    
oracletest:
  image: $REGISTRY/debian-node-oracle-docker
  stage: pre-build-test
  script:
    - echo 'Performing Oracle Test'
  tags:
    - CEP_RUNNER    

buildjob:
  stage: build
  script: 
    - echo "Building Image"
  tags:
    - CEP_RUNNER

lastcleanup:
  stage: cleanup
  script:
    - echo "Finishing CI CD"

